### ISSUE TITLE
Runtime exception when Lambda-Runtime-Trace-Id header not present

### ISSUE THREAD

**Issue by jlandahl** [zio/zio-lambda#130]
I'm trying to test a ZIO-Lambda project locally using the AWS SAM CLI. When trying to run it with `sam local invoke --invoke-image public.ecr.aws/sam/emulation-provided.al2` my function blows up with a NPE here: https://github.com/zio/zio-lambda/blob/master/lambda/src/main/scala/zio/lambda/internal/InvocationRequest.scala#L39

It appears the provided runtime API isn't returning the `Lambda-Runtime-Trace-Id` header.

Has anyone tried testing with `sam local invoke` and run into this problem?

**Comment by jrmsamson** [comment]
Hi @jlandahl, don't know what that runtime does but based on the docs, Lambda-Runtime-Trace-Id should be always there. [Check this out](https://docs.aws.amazon.com/lambda/latest/dg/runtimes-api.html). 

Not sure which is wrong, either the runtime that isn't returning the header properly or the doc that isn't reflecting that the header is optional

**Comment by jlandahl** [comment]
I'm guessing the runtime is wrong, though it appears to be providing the other three headers. Is there a way to modify `InvocationRequest` to deal with a potential missing header?

**Comment by nikolaylagutko** [comment]
Hey, had the same issue with NPE both on AWS Lambda Test and while running `sam local`
What I finally researched - once you didn't configure [AWS Tracing for you Lambda](https://docs.aws.amazon.com/lambda/latest/dg/services-xray.html) - this header will never come - that is cause this Exception - so part of the issue can be solved by [PR](https://github.com/zio/zio-lambda/pull/187) I prepared.
Unfortunately I still didn't find a way how to deal with this header and `sam local` :-(
