### ISSUE TITLE
Can we get a non-RC version of 1.0.0 deployed.

### ISSUE THREAD

**Issue by dbuschman7** [zio/zio-lambda#165]
It has been almost a year for the RC* status of 1.0 and I have to explain why it is not  yet published for 1.0 on ZIO 2.

What will it take to get this lib published under a non-RC 1.0.0 version?

**Comment by jrmsamson** [comment]
Hi there, I just published v1.0.0

**Comment by dbuschman7** [comment]
Woo Hoo ! 

Thanks for the quick response.

ZIO is the best!!
