### ISSUE TITLE
Custom layer is reinitialised on each request 

### ISSUE THREAD

**Issue by heaven-born** [zio/zio-lambda#197]
This is an example of the application with the custom layer `ConfigurationEnvironment` provided. 

```scala
object EntryPoint extends ZLambda[V2HttpEvent, V2HTTPResponse] { self =>

  override def apply(event: V2HttpEvent, context: Context): Task[V2HTTPResponse] =
    app(event,context).provideLayer(ConfigurationEnvironment.live)


  private def app(event: V2HttpEvent, context: Context) =
    for {
      _ <- ZIO.unit
    } yield V2HTTPResponse(200,Map(),Map(),List(), base64str,true)

}
```

This custom layer may contain heavy initialization logic that is expensive to execute on each request. 
But this is exactly what is happening with `ConfigurationEnvironment` because the layer is provided outside the app initialization logic. This way the application can't benefit from a warmed container. 

There must be a way to inject a layer to the code that initializes the whole lambda function process logic and propagate this layer to the `apply` method or something like this.

**Comment by heaven-born** [comment]
I spend some time investigating, and I think the way it must be done is by redesigning the application template structure. The application structure must be similar to what `zio-http` does and this will be also cross-zio project unification and more functional approach at the same time. 

Something like this:

```scala
object EntryPoint extends ZIOAppDefault {

  val app: ZLambdaApp[ConfigurationEnvironment, String] = ZLambdaApp.zio[KinesisEvent, String]{
    (request: KinesisEvent, context: Context) =>  for {
          _ <- ZIO.service[ConfigurationEnvironment]
    } yield "Handler ran successfully"
  }

  override val run =
    ZLambda.serve(app).provide(ConfigurationEnvironment.live)
}

```

**Comment by jrmsamson** [comment]
I did some investigation and before ZIO 2.0-RC5, this was totally fine, layers were always being reused and not being reinitialized in every invocation. I'll check this.

**Comment by heaven-born** [comment]
@jrmsamson If you confirm the issue, just let me know. I have a draft of this new app template structure implemented, so we can discuss it. The implementation is backward compatible with the ZLambda, so it will not break the old code.

**Comment by jrmsamson** [comment]
@heaven-born I confirmed this with the zio core team; apparently, this behaviour is expected since RC6. I don't think, it's a good idea to change the current interface. There are several ways we can make sure that the layer you provide isn't reinitialised in every invocation, you can either initialise your service before providing it to your effect.

```scala

object ConfigurationEnvironment {

  val service = new ConfigurationEnvironmentLive()
 
  val live = ZLayer.succeed(service)

}
```

or if you need to build your dependency graph by composing layers:

```scala


object EntryPoint extends ZLambda[V2HttpEvent, V2HTTPResponse] { self =>

  lazy val env = Unsafe.unsafe { implicit unsafe =>
    Runtime.default.unsafe.run(ZIO.scoped(ConfigurationEnvironment.live.build)).getOrThrowFiberFailure()
  }

  override def apply(event: V2HttpEvent, context: Context): Task[V2HTTPResponse] =
    app(event,context).provideEnvironment(env)


  private def app(event: V2HttpEvent, context: Context) =
    for {
      _ <- ZIO.unit
    } yield V2HTTPResponse(200,Map(),Map(),List(), base64str,true)

}
```

wdyt?

**Comment by heaven-born** [comment]
it looks a little bit hacky, isn't it? When people start creating something complex, they will definitely start asking and complaining because it is not an obvious thing to do. My guess is that `zio-http` app structure looks like it looks because they tried to handle this problem. And I think zio-http-like structure is also a bit more developer friendly from a type derivation perspective. 

Check this:

```scala
object EntryPoint extends ZIOAppDefault {

  val app = ZLambdaApp.zio { 
     (request: KinesisEvent, context: Context) =>  for {
          _ <- ZIO.service[ConfigurationEnvironment]
    } yield "Handler ran successfully"
  }

  override val run =
    ZLambdaApp
       .serve(app)
       .provide(ZLambdaApp.default, ConfigurationEnvironment.live)
}

```

A few app with different types can be combined here in a functional style way as well I guess. 

Taking into account that this is backward compatible and developers can still do their OOP-template-styled approach using `ZLambda ` it may be worth doing.

**Comment by jrmsamson** [comment]
ok makes sense. If you have already a draft for this please go ahead, we need to well document this too. Ideally, there should be just one way to implement ZLambda in the future. We can deprecate the existing one. Also, we need to make sure that this is also compatible when ZLambda is deployed as AWS Custom Layer.

**Comment by heaven-born** [comment]
what do we do with the tests, create a copy of each for the new style or just rewrite them and remove tests related to the old classes?  If you have some working env where you can test AWS Custom Layer, you can check out my branch and try it, because it may take a while for me to understand how to test it. The code for AWS Custom Layer looks relatively good already.

**Comment by heaven-born** [comment]
@jrmsamson regarding this AWS Custom Layer. I can't find the instruction on how to use it with `ZLambda` code. Is this supposed to be working with both lambda extension and the main lambda function compiled to the native image?  Because I'm observing a lot of class loading logic here, so I'm wondering how it works with native code. Can you give me an example of what should be done to configure this layer interaction logic?

**Comment by jrmsamson** [comment]
It looks like that there're not many people using zio-lambda as a custom layer as nobody has complained yet about Github releases not having the zip users can use to upload zio-lambda as lambda layer. in any case, we still need to support it because people can still benefit from it thanks to AWS Lambda Snapstart, but we need to document this.

But for your testing:

run ` sbt "zio-lambda / universal:packageBin"` 
which will generate a zip file in `./lambda/src/target/universal`

You need to upload this zip file to create the Custom layer. Follow the instructions described here: https://docs.aws.amazon.com/lambda/latest/dg/configuration-layers.html

Once you've done that, you need to upload your lambda funnction and choose the custom layer you just uploaded. For the lambda function, you can just use lambda-example and run 
`sbt "zio-lambda-example / assembly"` to create the jar

**Comment by jrmsamson** [comment]
One thing I'd like to point out is that users would only need to implement a single interface and be able to deploy their lambda functions in different ways, without any code change. Also, let's move any discussion about this change to the draft PR you've created.

**Comment by heaven-born** [comment]
I'm a little bit confused with this lambda functions uploading feature. How are lambda functions from the layers supposed to be used from the main function?

**Comment by jrmsamson** [comment]
forgot to mention that when packaging zip-lambda with sbt-native-packager, the main class is [ZLambdaRelectiveApp](https://github.com/zio/zio-lambda/blob/master/build.sbt#L61). This is basically the [custom runtime](https://docs.aws.amazon.com/lambda/latest/dg/runtimes-custom.html) built in zio-lambda. ZLambdaReflectiveApp will try to load your lambda function by reflection at the beginning of the invocation

**Comment by jrmsamson** [comment]
I'm leaning towards a different solution that would fix this easily.

**Comment by jrmsamson** [comment]
I'm leaning towards a much simpler solution. Something like

```scala
object SimpleHandler extends ZLambda[CustomEvent, String, ConfigurationEnvironment] {

  override val layer: ULayer[ConfigurationEnvironment] = ZLayer.succeed(ConfigurationEnvironment.live)

  override def apply(event: CustomEvent, context: Context): RIO[ConfigurationEnvironment, String] =
    for {
      _ <- ZIO.service[ConfigurationEnvironment]
    } yield "Handler ran successfully"

}

```

internally, we can just run

```scala
lazy val env = Unsafe.unsafe { implicit unsafe =>
    Runtime.default.unsafe.run(ZIO.scoped(layer.build)).getOrThrowFiberFailure()
}
```

and provide this env to the [applyJson](https://github.com/zio/zio-lambda/blob/master/lambda/src/main/scala/zio/lambda/ZLambda.scala#L13) method

**Comment by heaven-born** [comment]
Looks like this might work, but this solution has one weakness in comparison to zio-http-styled approach - type derivation. 
Even the original `ZLambda` requires providing types two times manually, but in this case, developers will have to provide a list of layers in a layer type manually as well. And I'm not sure if the solution that you proposed will work with multiple layers because all these macro running when "provide" is composing types. 

And compare this

```scala
object SimpleHandler extends ZLambda[CustomEvent, String, ConfigurationEnvironment] {

  override val layer = ZLayer.succeed(ConfigurationEnvironment.live)

  override def apply(event: CustomEvent, context: Context) =
    for {
      _ <- ZIO.service[ConfigurationEnvironment]
    } yield "Handler ran successfully"
}

```
And this

```scala 
object SimpleHandler extends ZIOAppDefault {

  val app = ZLambdaApp { 
     (request: CustomEvent, context: Context) =>  for {
          _ <- ZIO.service[ConfigurationEnvironment]
    } yield "Handler ran successfully"
  }

  override val run =
    ZLambdaApp
       .serve(app)
       .provide(ZLambdaApp.default, ConfigurationEnvironment.live)
}
```

The second one just has less background 'magic'  for the functional zio developers.

**Comment by jrmsamson** [comment]
I'm not so sure if your solution would work when zio-lambda is deployed as custom runtime. at some point you would need to load this function by reflection. Once you have this function, if you call `app` in this scenario, you would need to provide its environment which you don't have because you don't know how. On the other hand, you can also call `run`, which has all the environment fulfiled, but you'd end up in the same situation in which, the layer will be recreated in every invocation.

Unlike zio-http, zio-lambda can be deployed in different ways, and their nature are quite different. zio-lambda can be just a regular lambda function that will be loaded by our custom runtime, or have this custom runtime built-in so users can deploy it as a native binary.

**Comment by heaven-born** [comment]
>>or have this custom runtime built-in so users can deploy it as a native binary

This part is actually not very clear to me. I mean, I don't get how it works from the main lambda function perspective. How do we use it from there? Do we use it from the main function at all? Is this the case when calling "run" recreates the layer? Because if it does, then I assume that the solution that you proposed also does in this case. I mean, if calling the custom layer from the main function always restarts the application, then your solution will also restart the layer and it won't help.

I just don't understand the idea of deploying the layer with customer runtime, so I can't get why calling `run` restarts the layer in zio-http-like structure.

**Comment by heaven-born** [comment]
ah.. I think I started understanding your point. You are saying that `ZLambdaReflectiveApp` provides the env in its own part of the code, so there will be a missing evn with the approach that I propose.  In this case, your solution makes sense. I will think about it.

**Comment by heaven-born** [comment]
I think `run` call from `ZLambdaAppReflective` should do the job. This is because we provide a custom env outside the `loop` (`loopZioApp`) call. The only thing is that we will have to load `ZIOAppDefault` instead of app classes. 

What doesn't look good is that there is no place where to provide an error from the `Either` if we use `run`. 

Something like this:

```scala
  def run =
    LambdaLoader.loadLambdaApp.flatMap { v: Either[Throwable, ZIOAppDefault] =>
      ZIO.fromEither(v).flatMap(_.run)
    }.tapError {
      case throwable: Throwable =>
        RuntimeApi.sendInitializationError(
          InvocationErrorResponse.fromThrowable(throwable)
        )
      case any =>
        RuntimeApi.sendInitializationError(
          InvocationErrorResponse.fromThrowable(new IllegalStateException(any.toString))
        )
    }.provideSome(
      LambdaEnvironment.live,
      CustomClassLoader.live,
      LambdaAppLoaderLive.layer,
      RuntimeApiLive.layer
    )

```

**Comment by heaven-born** [comment]
I pushed this change to my branch, but I'm still not sure how to test it. When I deploy a zip generated by `universal:packageBin` as a layer and add this layer to my lambda function, is it supposed that both functions receive a copy of events?

**Comment by heaven-born** [comment]
That is how I'm trying to test: I created a lambda function in Java runtime, created a layer from a zip file generated by `universal:packageBin`, then added this layer to my function. Is it expected to observe messages from `SimpleHandler` when I run the "test" on the main function? 

I see that "bootstrap" file in the root of the project directory points to `zio-lambda` instead of `z-lambda-app-reflective`. Doesn't look correct.

**Comment by jrmsamson** [comment]
`universal:packageBin` will create a bunch of jar files with all the dependencies and zio-lambda. You need to provide a bootstrap executable file that AWS can use to run your custom runtime. The bootstrap file will execute the script `universal:packageBin` has generated that is named after the zio-lambda module. This script will run ZLambdaReflectiveApp that runs your lambda function implemented with zio-lambda by reflection and wait for the first aws event. you can read more about this [here](https://docs.aws.amazon.com/lambda/latest/dg/runtimes-custom.html).

That being said, once you have your layer uploaded, you just need to upload your lambda function and select zio-lambda a custom runtime.

<img width="315" alt="image" src="https://user-images.githubusercontent.com/7106508/233496248-789cd64a-1fa6-498f-aba6-1f9ed5113719.png">

As I mentioned before I can test this for you, if you don't manage to do it yourself. I'm also available in Discord in #zio channel if you need me to explain to you how all this works.

**Comment by jrmsamson** [comment]
> I think `run` call from `ZLambdaAppReflective` should do the job. This is because we provide a custom env outside the `loop` (`loopZioApp`) call. The only thing is that we will have to load `ZIOAppDefault` instead of app classes.
> 
> What doesn't look good is that there is no place where to provide an error from the `Either` if we use `run`.
> 
> Something like this:
> 
> ```scala
>   def run =
>     LambdaLoader.loadLambdaApp.flatMap { v: Either[Throwable, ZIOAppDefault] =>
>       ZIO.fromEither(v).flatMap(_.run)
>     }.tapError {
>       case throwable: Throwable =>
>         RuntimeApi.sendInitializationError(
>           InvocationErrorResponse.fromThrowable(throwable)
>         )
>       case any =>
>         RuntimeApi.sendInitializationError(
>           InvocationErrorResponse.fromThrowable(new IllegalStateException(any.toString))
>         )
>     }.provideSome(
>       LambdaEnvironment.live,
>       CustomClassLoader.live,
>       LambdaAppLoaderLive.layer,
>       RuntimeApiLive.layer
>     )
> ```

By the way, this soluton looks wrong to me. You only load the lambda function and nothing else. You need to load it and pass it to LoopProcessor so it can invoke the function when there's an event

**Comment by heaven-born** [comment]
I believe it may work because the new app format supposes that developer does this in `run` method in order to start the function for both regular and layer modes:

`  override val run =
    ZLambdaRunner.serve(app).provide(ZLambdaRunner.default,customLayer)`

And `ZLambdaRunner.serve(app)` passes the app to the loop processor. 

```scala
  def serve[R](app: ZLambdaApp[R, _, _]): RIO[R with LoopProcessor, Unit] =
    for {
      lp  <- ZIO.service[LoopProcessor]
      res <- lp.loopZioApp(Right(app))
    } yield res

```

**Comment by heaven-born** [comment]
I managed to configure the env for the testing, but looks like something is not 100% right, because it `ZLambdaAppReflective` throws ` java.lang.ClassNotFoundException: zio.lambda.example.SimpleHandler$` and I can't figure out why. May I ask you to check out my branch, run it and figure out what is happening?  

`ZLambdaAppReflective` is now switched to the new app structure, so If you build with `universal:packageBin` the new approach will be used.

**Comment by heaven-born** [comment]
Never mind, I found the issue, so now it is working. You can try and review the code. The layer is not re-initialized on each request anymore. 

Note that `case Left(throwable)` branch in `LoopProcessor` is not used anymore in the new approach, because this error can only be caught inside `ZLambdaAppReflective`. We must delete it along with deprecated functions in the future.  

btw, I'm wondering if we can apply implicit conversion here. In this case, the structure would become even less verbose:

```scala

object SimpleHandler extends ZIOAppDefault {

  def app(request: CustomEvent, context: Context) =  for {
      _ <- ZIO.service[ConfigurationEnvironment]
  } yield "Handler ran successfully"

  override val run =
    ZLambdaApp
       .serve(app)
       .provide(ZLambdaApp.default, ConfigurationEnvironment.live)
}

```

**Comment by heaven-born** [comment]
Yeah, I see that the approach with the plain function is doable even without implicits. In this case, we won't need `ZLambdaApp` at all.  Let me know if you think we should do it too. ~~The idea is to pass the function `app` to the `serve` and also allow passing an optional parameter for the function `applyJson`  to override default behavior if needed.~~ The idea is to provide two overloaded methods of `serve` one for regular function, and the other one for applyJson-like `(json: String, context: Context)` function signature. If a regular function is provided, then it will be called by the default implementation of applyJson-like function internally. If the version of `serve` with applyJson-like function signature is called, then the developer will work with a lower level of code and will be responsible for encoding and decoding.

**Comment by heaven-born** [comment]
It was too easy to implement, so I just did. Now the app structure looks like this:

```scala
object SimpleHandler extends ZIOAppDefault {

  def app(request: CustomEvent, context: Context) =  for {
      _ <- ZIO.service[ConfigurationEnvironment]
  } yield "Handler ran successfully"

  override val run =
    ZLambdaApp
       .serve(app)
       .provide(ZLambdaApp.default, ConfigurationEnvironment.live)
}
```

Ready for review.

**Comment by heaven-born** [comment]
I've just realized that with this change `zio-lambda` also becomes json parser agnostic. Developers can always implement `raw` function that uses Circe for example, wrap their regular app in this raw function and pass it to `ZLambdaApp.serveRaw(...)`.
