### ISSUE TITLE
GLIBC_2.32 Missing Error with gcr.io/distroless/base in zio-lambda Docker Containers

### ISSUE THREAD

**Issue by kijuky** [zio/zio-lambda#256]
# Description:
When utilizing lambda functions within Docker containers with the zio-lambda library, an error occurs due to the absence of GLIBC_2.32 when using gcr.io/distroless/base. This issue can be resolved by switching to gcr.io/distroless/base-debian12.

# Steps to Reproduce:
1. Set up a lambda function within a Docker container using gcr.io/distroless/base.
2. Attempt to execute the lambda function.
3. Encounter GLIBC_2.32 missing error.
# Expected Behavior:
Lambda function should execute without errors.

# Actual Behavior:
GLIBC_2.32 missing error occurs, hindering the execution of the lambda function.

# Resolution:
Switching to gcr.io/distroless/base-debian12 resolves this issue.

# Documentation Update:
The documentation at https://github.com/zio/zio-lambda/blob/master/docs/index.md?plain=1#L91 should be updated to reflect this resolution.

# Reference Information:
- Related Issue: https://github.com/GoogleContainerTools/distroless/issues/1342#issuecomment-1881646615

**Comment by jrmsamson** [comment]
Thanks for reporting, I'll look into it
