### ISSUE TITLE
Full example project

### ISSUE THREAD

**Issue by francisdb** [zio/zio-lambda#84]
Do you have a full example project one can easily test / deploy?
Including all required sbt config for a graalvm setup?

**Comment by jrmsamson** [comment]
Hi @francisdb,

Check out the lambda-example module and also the build.sbt file of this project. You'll see there the minimum graalvm options that you lambda function will need

**Comment by francisdb** [comment]
By the way, I ended up here because of your zio world talk!

I still think a standalone example that also explains how to get started on aws with this would be better

**Comment by jrmsamson** [comment]
Sure no worries. I'll see what I can do

**Comment by francisdb** [comment]
Maybe just some more documentation on the setup / getting started part would be enough?

What needs to be in your sbt project including graalvm setup?
How do your test your function locally?
How do you upload the resulting function and make it available as http endpoint?

**Comment by jrmsamson** [comment]
HI @francisdb, this PR got merged https://github.com/zio/zio-lambda/pull/97, which includes an update of the README. hope that's enough to get started

**Comment by francisdb** [comment]
Much better, thanks, maybe you can also add some section regarding the needed build.sbt settings / plugins for graal?
